version: '3'

services:
  db:
    image: postgres:9.6.2-alpine
    restart: always
    env_file:
      - ./docker/environments
    volumes:
      - ./pg_data:/var/lib/postgresql/9.6/main
    ports:
      - "5432:5432"
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./docker/environments